// state.js（使用对象包装以允许修改）
export const state = {
    current_mode: null,
    // is_skyscraper_mode: false,
    // is_vx_mode: false,
    current_grid_size: 0,
    is_candidates_mode: false,
    is_solve_mode: false,
    originalBoard: null, // 备份原始题目状态
    isShowingSolution: false, // 是否正在显示答案
    solution: null,
    // solution_Count: 0,
    silentMode: false,
    candidate_elimination_score: {},
    total_score_sum: 0,

    clues_board: null,
    marks_board: null,
    inequality_marks: null,
    _inequality_constraint_cache: null,

    box_missing_subsets: {},
    row_missing_subsets: {},
    col_missing_subsets: {},
    multi_diagonal_lines: [],
    solve_stats: {
        solution_count: 0,
        technique_counts: {},
        total_score: 0,
    },
    check_next: false,
    techniqueScoreMultipliers: {
        Box_Elimination: 1,
        Box_Elimination_1: 1,
        Box_Elimination_2: 1,
        Box_Elimination_3: 1,
        Box_Elimination_4: 1,
        Box_Elimination_5: 1,
        Box_Elimination_6: 1,
        Box_Elimination_7: 1,
        Box_Elimination_8: 1,
        Box_Elimination_9: 1,
        Row_Col_Elimination: 1,
        Row_Col_Elimination_1: 1,
        Row_Col_Elimination_2: 1,
        Row_Col_Elimination_3: 1,
        Row_Col_Elimination_4: 1,
        Row_Col_Elimination_5: 1,
        Row_Col_Elimination_6: 1,
        Row_Col_Elimination_7: 1,
        Row_Col_Elimination_8: 1,
        Row_Col_Elimination_9: 1,
        Extra_Region_Elimination: 1,
        Extra_Region_Elimination_1: 1,
        Extra_Region_Elimination_2: 1,
        Extra_Region_Elimination_3: 1,
        Extra_Region_Elimination_4: 1,
        Extra_Region_Elimination_5: 1,
        Extra_Region_Elimination_6: 1,
        Extra_Region_Elimination_7: 1,
        Extra_Region_Elimination_8: 1,
        Extra_Region_Elimination_9: 1,
        Box_Block: 1,
        Box_Block_2: 1,
        Box_Block_3: 1,
        Box_Block_4: 1,
        Box_Block_5: 1,
        Box_Block_6: 1,
        Box_Block_7: 1,
        Box_Block_8: 1,
        Box_Block_9: 1,
        Row_Col_Block: 1,
        Row_Col_Block_2: 1,
        Row_Col_Block_3: 1,
        Row_Col_Block_4: 1,
        Row_Col_Block_5: 1,
        Row_Col_Block_6: 1,
        Row_Col_Block_7: 1,
        Row_Col_Block_8: 1,
        Row_Col_Block_9: 1,
        Variant_Box_Block: 1,
        Variant_Box_Block_2: 1,
        Variant_Box_Block_3: 1,
        Variant_Box_Block_4: 1,
        Variant_Box_Block_5: 1,
        Variant_Box_Block_6: 1,
        Variant_Box_Block_7: 1,
        Variant_Box_Block_8: 1,
        Variant_Box_Block_9: 1,
        Variant_Row_Col_Block: 1,
        Variant_Row_Col_Block_2: 1,
        Variant_Row_Col_Block_3: 1,
        Variant_Row_Col_Block_4: 1,
        Variant_Row_Col_Block_5: 1,
        Variant_Row_Col_Block_6: 1,
        Variant_Row_Col_Block_7: 1,
        Variant_Row_Col_Block_8: 1,
        Variant_Row_Col_Block_9: 1,
        Extra_Region_Block: 1,
        Extra_Region_Block_2: 1,
        Extra_Region_Block_3: 1,
        Extra_Region_Block_4: 1,
        Extra_Region_Block_5: 1,
        Extra_Region_Block_6: 1,
        Extra_Region_Block_7: 1,
        Extra_Region_Block_8: 1,
        Extra_Region_Block_9: 1,
        Variant_Extra_Region_Block: 1,
        Variant_Extra_Region_Block_2: 1,
        Variant_Extra_Region_Block_3: 1,
        Variant_Extra_Region_Block_4: 1,
        Variant_Extra_Region_Block_5: 1,
        Variant_Extra_Region_Block_6: 1,
        Variant_Extra_Region_Block_7: 1,
        Variant_Extra_Region_Block_8: 1,
        Variant_Extra_Region_Block_9: 1,
        Box_Pair_Block: 1,
        Extra_Region_Pair_Block: 1,
        Box_Hidden_Pair: 1,
        Row_Col_Hidden_Pair: 1,
        Extra_Region_Hidden_Pair: 1,
        Box_Naked_Pair: 1,
        Row_Col_Naked_Pair: 1,
        Extra_Region_Naked_Pair: 1,
        Box_Hidden_Triple: 1,
        Row_Col_Hidden_Triple: 1,
        Extra_Region_Hidden_Triple: 1,
        Box_Naked_Triple: 1,
        Row_Col_Naked_Triple: 1,
        Extra_Region_Naked_Triple: 1,
        Box_Hidden_Quad: 1,
        Row_Col_Hidden_Quad: 1,
        Extra_Region_Hidden_Quad: 1,
        Box_Naked_Quad: 1,
        Row_Col_Naked_Quad: 1,
        Extra_Region_Naked_Quad: 1,
        Cell_Elimination_1: 1,
        Cell_Elimination_2: 1,
        Cell_Elimination_3: 1,
        Cell_Elimination_4: 1,
        Cell_Elimination_5: 1,
        Cell_Elimination_6: 1,
        Cell_Elimination_7: 1,
        Cell_Elimination_8: 1,
        Cell_Elimination_9: 1,
        special_combination_must_not_contain: 1,
        Special_Combination_Region_Most_Not_Contain_1: 1,
        Special_Combination_Region_Most_Not_Contain_2: 1,
        Special_Combination_Region_Most_Not_Contain_3: 1,
        Special_Combination_Region_Most_Not_Contain_4: 1,
        Special_Combination_Region_Most_Not_Contain_n: 1,
        special_combination_must_contain: 1,
        Special_Combination_Region_Most_Contain_1: 1,
        Special_Combination_Region_Most_Contain_2: 1,
        Special_Combination_Region_Most_Contain_3: 1,
        Special_Combination_Region_Most_Contain_4: 1,
        Special_Combination_Region_Most_Contain_n: 1,
        special_combination_cell_elimination: 1,
        Special_Combination_Region_Cell_Elimination_1: 1,
        Special_Combination_Region_Cell_Elimination_2: 1,
        Special_Combination_Region_Cell_Elimination_3: 1,
        Special_Combination_Region_Cell_Elimination_4: 1,
        Special_Combination_Region_Cell_Elimination_n: 1,
        special_combination_elimination: 1,
        Special_Combination_Region_Elimination_1: 1,
        Special_Combination_Region_Elimination_2: 1,
        Special_Combination_Region_Elimination_3: 1,
        Special_Combination_Region_Elimination_4: 1,
        Special_Combination_Region_Elimination_n: 1,
        special_combination_block: 1,
        Special_Combination_Region_Block_1: 1,
        Special_Combination_Region_Block_2: 1,
        Special_Combination_Region_Block_3: 1,
        Special_Combination_Region_Block_4: 1,
        Special_Combination_Region_Block_n: 1,
        multi_special_combination: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_1: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_2: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_3: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_4: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_n: 1,
        Multi_Special_Combination_Region_Most_Contain_1: 1,
        Multi_Special_Combination_Region_Most_Contain_2: 1,
        Multi_Special_Combination_Region_Most_Contain_3: 1,
        Multi_Special_Combination_Region_Most_Contain_4: 1,
        Multi_Special_Combination_Region_Most_Contain_n: 1,
        Multi_Special_Combination_Region_Cell_Elimination_1: 1,
        Multi_Special_Combination_Region_Cell_Elimination_2: 1,
        Multi_Special_Combination_Region_Cell_Elimination_3: 1,
        Multi_Special_Combination_Region_Cell_Elimination_4: 1,
        Multi_Special_Combination_Region_Cell_Elimination_n: 1,
        Multi_Special_Combination_Region_Elimination_1: 1,
        Multi_Special_Combination_Region_Elimination_2: 1,
        Multi_Special_Combination_Region_Elimination_3: 1,
        Multi_Special_Combination_Region_Elimination_4: 1,
        Multi_Special_Combination_Region_Elimination_n: 1,
        Multi_Special_Combination_Region_Block_1: 1,
        Multi_Special_Combination_Region_Block_2: 1,
        Multi_Special_Combination_Region_Block_3: 1,
        Multi_Special_Combination_Region_Block_4: 1,
        Multi_Special_Combination_Region_Block_n: 1,
    },
};

// 设置当前模式(会自动取消其他模式)
export function set_current_mode(mode) {
    if ([
        'classic',
        'skyscraper',
        'VX',
        'kropki',
        'consecutive',
        'candidates',
        'missing',
        'consecutive',
        'diagonal',
        'anti_diagonal',
        'hashtag',
        'multi_diagonal',
        'window',
        'pyramid',
        'extra_region',
        'renban',
        'fortress',
        'clone',
        'exclusion',
        'quadruple',
        'add',
        'product',
        'ratio',
        'inequality',
        'odd',
        'odd_even',
        'isomorphic',
        'anti_king',
        'anti_knight',
        'anti_elephant',
        'palindrome',
        'X_sums',
        'sandwich',
        'new'
    ].includes(mode)) {
        state.current_mode = mode;
    } else {
        state.current_mode = null;
    }
}