// state.js（使用对象包装以允许修改）
export const state = {
    current_mode: null,
    is_full_mark_mode: false,
    // is_skyscraper_mode: false,
    // is_vx_mode: false,
    current_grid_size: 0,
    is_candidates_mode: false,
    is_solve_mode: false,
    originalBoard: null, // 备份原始题目状态
    isShowingSolution: false, // 是否正在显示答案
    solution: null,
    // solution_Count: 0,
    silentMode: false,
    candidate_elimination_score: {},
    total_score_sum: 0,

    clues_board: null,
    marks_board: null,
    inequality_marks: null,
    _inequality_constraint_cache: null,
    thermo_marks: null,
    _thermo_constraint_cache: null,

    box_missing_subsets: {},
    row_missing_subsets: {},
    col_missing_subsets: {},
    multi_diagonal_lines: [],
    solve_stats: {
        solution_count: 0,
        technique_counts: {},
        total_score: 0,
    },
    check_next: false,
    techniqueScoreMultipliers: {
        Box_Elimination: 1,
        Box_Elimination_1: 2,
        Box_Elimination_2: 2,
        Box_Elimination_3: 2,
        Box_Elimination_4: 3,
        Box_Elimination_5: 3,
        Box_Elimination_6: 3,
        Box_Elimination_7: 4,
        Box_Elimination_8: 4,
        Box_Elimination_9: 4,
        Row_Col_Elimination: 1,
        Row_Col_Elimination_1: 1,
        Row_Col_Elimination_2: 2,
        Row_Col_Elimination_3: 5,
        Row_Col_Elimination_4: 20,
        Row_Col_Elimination_5: 50,
        Row_Col_Elimination_6: 80,
        Row_Col_Elimination_7: 90,
        Row_Col_Elimination_8: 100,
        Row_Col_Elimination_9: 110,
        Extra_Region_Elimination: 1,
        Extra_Region_Elimination_1: 2,
        Extra_Region_Elimination_2: 2,
        Extra_Region_Elimination_3: 2,
        Extra_Region_Elimination_4: 3,
        Extra_Region_Elimination_5: 3,
        Extra_Region_Elimination_6: 3,
        Extra_Region_Elimination_7: 4,
        Extra_Region_Elimination_8: 4,
        Extra_Region_Elimination_9: 4,
        Box_Block: 1,
        Box_Block_2: 10,
        Box_Block_3: 12,
        Box_Block_4: 14,
        Box_Block_5: 16,
        Box_Block_6: 18,
        Box_Block_7: 20,
        Box_Block_8: 22,
        Box_Block_9: 24,
        Row_Col_Block: 1,
        Row_Col_Block_2: 40,
        Row_Col_Block_3: 48,
        Row_Col_Block_4: 56,
        Row_Col_Block_5: 64,
        Row_Col_Block_6: 72,
        Row_Col_Block_7: 80,
        Row_Col_Block_8: 88,
        Row_Col_Block_9: 96,
        Variant_Box_Block: 1,
        Variant_Box_Block_2: 20,
        Variant_Box_Block_3: 30,
        Variant_Box_Block_4: 80,
        Variant_Box_Block_5: 100,
        Variant_Box_Block_6: 120,
        Variant_Box_Block_7: 140,
        Variant_Box_Block_8: 160,
        Variant_Box_Block_9: 180,
        Variant_Row_Col_Block: 1,
        Variant_Row_Col_Block_2: 70,
        Variant_Row_Col_Block_3: 120,
        Variant_Row_Col_Block_4: 150,
        Variant_Row_Col_Block_5: 160,
        Variant_Row_Col_Block_6: 170,
        Variant_Row_Col_Block_7: 180,
        Variant_Row_Col_Block_8: 190,
        Variant_Row_Col_Block_9: 200,
        Extra_Region_Block: 1,
        Extra_Region_Block_2: 20,
        Extra_Region_Block_3: 30,
        Extra_Region_Block_4: 34,
        Extra_Region_Block_5: 34,
        Extra_Region_Block_6: 34,
        Extra_Region_Block_7: 40,
        Extra_Region_Block_8: 40,
        Extra_Region_Block_9: 40,
        Variant_Extra_Region_Block: 1,
        Variant_Extra_Region_Block_2: 20,
        Variant_Extra_Region_Block_3: 30,
        Variant_Extra_Region_Block_4: 80,
        Variant_Extra_Region_Block_5: 100,
        Variant_Extra_Region_Block_6: 120,
        Variant_Extra_Region_Block_7: 140,
        Variant_Extra_Region_Block_8: 160,
        Variant_Extra_Region_Block_9: 180,
        Box_Pair_Block: 40,
        Extra_Region_Pair_Block: 60,
        Box_Hidden_Pair: 30,
        Row_Col_Hidden_Pair: 200,
        Extra_Region_Hidden_Pair: 40,
        Box_Naked_Pair: 80,
        Row_Col_Naked_Pair: 90,
        Extra_Region_Naked_Pair: 120,
        Box_Hidden_Triple: 70,
        Row_Col_Hidden_Triple: 400,
        Extra_Region_Hidden_Triple: 100,
        Box_Naked_Triple: 250,
        Row_Col_Naked_Triple: 300,
        Extra_Region_Naked_Triple: 340,
        Box_Hidden_Quad: 350,
        Row_Col_Hidden_Quad: 600,
        Extra_Region_Hidden_Quad: 600,
        Box_Naked_Quad: 500,
        Row_Col_Naked_Quad: 550,
        Extra_Region_Naked_Quad: 550,
        Cell_Elimination_1: 1,
        Cell_Elimination_2: 2,
        Cell_Elimination_3: 5,
        Cell_Elimination_4: 20,
        Cell_Elimination_5: 50,
        Cell_Elimination_6: 80,
        Cell_Elimination_7: 90,
        Cell_Elimination_8: 100,
        Cell_Elimination_9: 110,
        special_combination_must_not_contain: 1,
        Special_Combination_Region_Most_Not_Contain_1: 1,
        Special_Combination_Region_Most_Not_Contain_2: 3,
        Special_Combination_Region_Most_Not_Contain_3: 30,
        Special_Combination_Region_Most_Not_Contain_4: 80,
        Special_Combination_Region_Most_Not_Contain_n: 200,
        special_combination_must_contain: 1,
        Special_Combination_Region_Most_Contain_1: 3,
        Special_Combination_Region_Most_Contain_2: 3,
        Special_Combination_Region_Most_Contain_3: 3,
        Special_Combination_Region_Most_Contain_4: 3,
        Special_Combination_Region_Most_Contain_n: 5,
        special_combination_cell_elimination: 1,
        Special_Combination_Region_Cell_Elimination_1: 1,
        Special_Combination_Region_Cell_Elimination_2: 3,
        Special_Combination_Region_Cell_Elimination_3: 80,
        Special_Combination_Region_Cell_Elimination_4: 150,
        Special_Combination_Region_Cell_Elimination_n: 500,
        special_combination_elimination: 1,
        Special_Combination_Region_Elimination_1: 2,
        Special_Combination_Region_Elimination_2: 5,
        Special_Combination_Region_Elimination_3: 50,
        Special_Combination_Region_Elimination_4: 100,
        Special_Combination_Region_Elimination_n: 300,
        special_combination_block: 1,
        Special_Combination_Region_Block_1: 15,
        Special_Combination_Region_Block_2: 25,
        Special_Combination_Region_Block_3: 80,
        Special_Combination_Region_Block_4: 150,
        Special_Combination_Region_Block_n: 400,
        multi_special_combination: 1,
        Multi_Special_Combination_Region_Most_Not_Contain_1: 15,
        Multi_Special_Combination_Region_Most_Not_Contain_2: 30,
        Multi_Special_Combination_Region_Most_Not_Contain_3: 80,
        Multi_Special_Combination_Region_Most_Not_Contain_4: 150,
        Multi_Special_Combination_Region_Most_Not_Contain_n: 500,
        Multi_Special_Combination_Region_Most_Contain_1: 15,
        Multi_Special_Combination_Region_Most_Contain_2: 30,
        Multi_Special_Combination_Region_Most_Contain_3: 80,
        Multi_Special_Combination_Region_Most_Contain_4: 150,
        Multi_Special_Combination_Region_Most_Contain_n: 500,
        Multi_Special_Combination_Region_Cell_Elimination_1: 15,
        Multi_Special_Combination_Region_Cell_Elimination_2: 30,
        Multi_Special_Combination_Region_Cell_Elimination_3: 80,
        Multi_Special_Combination_Region_Cell_Elimination_4: 150,
        Multi_Special_Combination_Region_Cell_Elimination_n: 500,
        Multi_Special_Combination_Region_Elimination_1: 30,
        Multi_Special_Combination_Region_Elimination_2: 50,
        Multi_Special_Combination_Region_Elimination_3: 80,
        Multi_Special_Combination_Region_Elimination_4: 150,
        Multi_Special_Combination_Region_Elimination_n: 500,
        Multi_Special_Combination_Region_Block_1: 15,
        Multi_Special_Combination_Region_Block_2: 30,
        Multi_Special_Combination_Region_Block_3: 80,
        Multi_Special_Combination_Region_Block_4: 150,
        Multi_Special_Combination_Region_Block_n: 500,
    
        "一刀流宫排除": 2,
        "一刀流宫区块": 10,
        "打表": 5,
        "欠一宫数对": 200,
        "欠一宫三数组": 400,
        "欠一宫四数组": 600,
        "欠一行列数对": 400,
        "欠一行列三数组": 600,
        "欠一行列四数组": 800,
    },
};

const FULL_MARK_MODES = ['five_six', 'VX', 'consecutive', 'kropki'];

// 设置当前模式(会自动取消其他模式)
export function set_current_mode(mode) {
    if ([
        'classic',
        'skyscraper',
        'VX',
        'kropki',
        'consecutive',
        'candidates',
        'missing',
        'consecutive',
        'diagonal',
        'anti_diagonal',
        'hashtag',
        'multi_diagonal',
        'window',
        'pyramid',
        'extra_region',
        'renban',
        'fortress',
        'clone',
        'exclusion',
        'inclusion',
        'quadruple',
        'add',
        'five_six',
        'product',
        'ratio',
        'inequality',
        'thermo',
        'odd',
        'odd_even',
        'isomorphic',
        'anti_king',
        'anti_knight',
        'anti_elephant',
        'palindrome',
        'X_sums',
        'sandwich',
        'new'
    ].includes(mode)) {
        state.current_mode = mode;
        state.is_full_mark_mode = FULL_MARK_MODES.includes(mode);
    } else {
        state.current_mode = null;
        state.is_full_mark_mode = false;
    }
}